[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
send_message = '0x9b2c7263883399c64ab0f4890b50383253f188e7b01a7a4d668e40134a296e02'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]